version: '3.8'

services:
  vprodb:
    build:
      context: ./Docker-files/db
    image: "otunsdiary/vprodb"
    container_name: "vprodb"
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
      - MYSQL_DATABASE=vprodb
      - MYSQL_USER=vprodb
      - MYSQL_PASSWORD=vprodb

  redis:
    image: "redis:alpine"

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    build:
      context: ./Docker-files/app
    image: "otunsdiary/vproapp"
    container_name: "vproapp"
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vprowebb:
    build:
      context: ./Docker-files/web
    image: "otunsdiary/vproweb"
    container_name: "vproweb"
    ports:
      - "80:80"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

volumes:
  vprodbdata:
  vproappdata:
